name: PRs

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]
        poetry-version: [1.2.1]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.1.3
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install Dependencies
        run: |
          poetry install --no-root
      - name: Lint with flake8/pylint
        run: |
          # stop the build if there are Python syntax errors or undefined names
          poetry run flake8 pyconsul/
          poetry run pylint pyconsul/
          poetry run mypy pyconsul/
      - name: Test with pytest
        run: |
          poetry run pytest --cov=pyconsul tests/ --junitxml=report.xml --cov-report xml
